### ISSUE TITLE
Deployment guide

### ISSUE THREAD

**Issue by pudgereyem** [genesis/wordpress#140]
Hi!
I want to use this project but have not used Capistrano before – and I can't see any guide(s) here on how to deploy with Genesis? Have someone written a tutorial or something?

The information in the README here is lacking I feel.

**Comment by EvanK** [comment]
Genesis is intended to run on Ubuntu 12.04 (which comes with Apache 2.2), and will definitely break on 14.04 (which comes with Apache 2.4).

Evolution uses 14.04 and _should_ gracefully handle either Apache minor version. I'd say it's beta stable, in that it's usable but some of the internals are still changing and we're sussing out bugs and putting together docs
