### ISSUE TITLE
Deployment questions

### ISSUE THREAD

**Issue by rs13** [genesis/wordpress#141]
Hello Eric,

I have been looking for a wordpress deployment framework using vagrant and came across yours. I followed your documentation closely but have several questions:

1. What does the remote server (the one that runs wordpress for public to view) have to have installed? Are there any instructions for the server install? Which parts of your installation checklist do I need to install on the remote server?

2. For my local environment that I provision using vagrant up, can I load for example Varying-Vagrant-Vagrants? Or does it have to be just plain let's say Ubuntu VM box?  I guess I am not clear what does your scaffolding install and how do I control what version of all the installed packages are to make sure that I match those on the remote server.

3. I noticed https://github.com/evolution link. Are you working on replacing the genesis framework for a new version? If so, how will one be able to migrate the existing genesis one?

**Comment by EvanK** [comment]
Sorry for the lack of response. We got busy on other projects, and I'm just now coming back to the backlog of issues!

1. Genesis requires Ubuntu 12.04 (its successor [Evolution](https://github.com/evolution/wordpress) is built on 14.04)
2. I've honestly never used VVV, but it might be usable with Genesis. I would not say that we officially support it, however
3. Yes, this is intended as a replacement/successor to Genesis. We do not currently have a working migration path, but it's on our roadmap
