### ISSUE TITLE
Is it safe to upgrade Ubuntu?

### ISSUE THREAD

**Issue by AntJanus** [genesis/wordpress#147]
I know that running Genesis on Ubuntu 14.04 is currently not supported; however, if I have a 12.04/12.10 machine and run `do-release-upgrade`, will I able to keep Genesis running? If I understand the upgrade process correctly, it shouldn't overwrite any of these settings.

And I'd really like to safely update!

**Comment by EvanK** [comment]
The only major issue you may run across is if Apache is upgraded from 2.2 to 2.4 in the process.

There are some [changes within apache itself](http://httpd.apache.org/docs/2.4/upgrading.html), as well as changes in Ubuntu's structure of the apache configs and and `a2en{mod,site,conf}` commands

**Comment by EvanK** [comment]
I'm curious, did you attempt this and was it successful?

If you want to try & get your existing site ported to Evolution, we could use some test subjects for [the Cambrian importer](https://github.com/evolution/wordpress/pull/66#issuecomment-126815979) :neckbeard:

**Comment by AntJanus** [comment]
It wasn't. I upgraded to 14.04, and got a white page of death. Didn't really have time to investigate it so I decided not to push into it further.
