### ISSUE TITLE
ENOENT Error

### ISSUE THREAD

**Issue by amakk** [genesis/wordpress#148]
Hi, this looks like a really interesting project and I'm eager to try it out, but I'm getting the following error during scaffolding:

```
   create deployment/stages/production.rb
     info Installing Gems...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn bundle ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
```

I used example.com for repository and domain name, and all the defaults after that. I'm on OS X 10.10.3 and my ruby version is:

`ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]`

**Comment by EvanK** [comment]
Do you have [bundler](http://bundler.io/) installed? That is what's being called to install gems:

> https://github.com/genesis/wordpress/blob/544e13c4e5346bf525d5220e04b860e0bd388415/generator/app/index.js#L392

**Comment by EvanK** [comment]
Also, if you're just starting out, I would recommend using [Evolution](https://github.com/evolution/wordpress). Genesis is pretty much at end of life, and that is the successor

**Comment by amakk** [comment]
Hi Evan, 

Thank you, I will check out Evolution, it looks even better. I'll also try installing bundler and will see if that fixes the issue. Apologize for delayed reply as I was traveling.

**Comment by amakk** [comment]
Oops, I forgot that this is still open. For anyone curious, installing bundler fixed my issue, though I am now using evolution as Evan suggested.
