### ISSUE TITLE
No permission access to wp-admin/install.php if accessed by IP

### ISSUE THREAD

**Issue by guicoma** [genesis/wordpress#150]
I recently discovered genesis-wordpress and it seems very promising!

The setup process went fine and everything seemed to be going smoothly.
However after doing `vagrant up` I stumbled upon a "403 Forbidden" error message when accessing the host. Precisely "You don't have permission to access /wp-admin/install.php on this server.".

After some research I somehow boiled down the issue to the .htaccess file.  It seems to be that since I was accessing the server through the IP address instead of the local.{Domain name} the access to the install file was being denied.

I guess my question is: Is this like this for security reasons or would it be possible to also consider the IP address in the initial .htaccess?

**Comment by ericrasch** [comment]
@guicoma You are correct... it was for security reasons. @EvanK might be able to comment on how setting an IP would work, but for now, if you disable these lines in your root `.htaccess` file, you should be able to get around that: https://github.com/genesis/wordpress/blob/master/generator/app/templates/web/htaccess#L80-L85

**Comment by EvanK** [comment]
Since the vagrant's ip address can vary (it is set during yeoman generation), it would be difficult to take that into account for the htaccess restrictions -- doubly so since the source ip apache sees would not be the address of the _vagrant_, but of the _host_ machine.

If at all possible, I would recommend using the `local.` hostname rather than directly by ip

**Comment by EvanK** [comment]
While I'm making recommendations, I should also say that Genesis is reaching end-of-life, and its successor, [Evolution](https://github.com/evolution/wordpress), is more actively supported.

**Comment by guicoma** [comment]
Thank you @ericrasch I was able to get over the bump disabling those lines at first. Also thank you @EvanK for the heads up. I'll be taking a look at Evolution for future projects.

**Comment by shangelina** [comment]
Hi there, I would like to join this discussion cause I have a similar problem too!
I was setting the plugin "ithemes security" and something crashed and now I have as well the error "403 No permission" 
I looked around many forums but couldn't fix the problem. In the htacccess I see many code lines wrote by itheme security, if I remove them the site doesn't come back but shows to the "installing wordpress launch page"
Same thing if I try to rename htaccess... the site shows the "installing wordpress launch page"
I'm kinda disperate right now, could you help me someway? (I can also paste the htaccess code here if you require)
Thank you soo much!

**Comment by EvanK** [comment]
What changes did said plugin make to the htaccess? Do you know if it made any major changes to the database (added tables, or added data to the meta tables)?

**Comment by shangelina** [comment]
HI Evank! Thanks for the reply =D
I paste down here the rules added by itheme security to the htaccess.
Unfortunetly i dunno if it changes the database tables, i believe it did right now, but still have no access to the myphpadmin panel (I asked to the technician to give it to me, but he still it didn't reply)
Right now I think the only solution is to restore an old version of database, but I'm not sure this is the right solution (plus, I can't really do it, cause as I said - i can't access to it LOL)

here's the code. As I sai, if I try to remove this code, the site goes to the "install wordpress" welcome page
 
# BEGIN iThemes Security - Do not modify or remove this line
# iThemes Security Config Details: 2
	# Enable the hide backend feature - Security > Settings > Hide Login Area > Hide Backend
	# RewriteRule ^(/)?hesislog/?$ /wp-login.php [QSA,L]

	# Protect System Files - Security > Settings > System Tweaks > System Files
	<files .htaccess>
		<IfModule mod_authz_core.c>
			Require all denied
		</IfModule>
		<IfModule !mod_authz_core.c>
			Order allow,deny
			Deny from all
		</IfModule>
	</files>
    
	<files readme.html>
		<IfModule mod_authz_core.c>
			Require all denied
		</IfModule>
		<IfModule !mod_authz_core.c>
			Order allow,deny
			Deny from all
		</IfModule>
	</files>
	<files readme.txt>
		<IfModule mod_authz_core.c>
			Require all denied
		</IfModule>
		<IfModule !mod_authz_core.c>
			Order allow,deny
			Deny from all
		</IfModule>
	</files>
	        <files install.php>
		<IfModule mod_authz_core.c>
			Require all denied
		</IfModule>
		<IfModule !mod_authz_core.c>
			Order allow,deny
			Deny from all
		</IfModule>
	</files>    
       <files wp-config.php>
		<IfModule mod_authz_core.c>
			Require all denied
		</IfModule>
		<IfModule !mod_authz_core.c>
			Order allow,deny
			Deny from all
		</IfModule>
	</files>

	# Disable Directory Browsing - Security > Settings > System Tweaks > Directory Browsing
	Options -Indexes

	<IfModule mod_rewrite.c>
		RewriteEngine On
            
	# Protect System Files - Security > Settings > System Tweaks > System Files
		RewriteRule ^wp-admin/includes/ - [F]
		RewriteRule !^wp-includes/ - [S=3]
		RewriteCond %{SCRIPT_FILENAME} !^(.*)wp-includes/ms-files.php
		RewriteRule ^wp-includes/[^/]+\.php$ - [F]
		RewriteRule ^wp-includes/js/tinymce/langs/.+\.php - [F]
		RewriteRule ^wp-includes/theme-compat/ - [F]

		# Disable PHP in Uploads - Security > Settings > System Tweaks > Uploads
		RewriteRule ^wp\-content/uploads/.*\.(?:php[1-6]?|pht|phtml?)$ - [NC,F]

		# Filter Request Methods - Security > Settings > System Tweaks > Request Methods
		RewriteCond %{REQUEST_METHOD} ^(TRACE|DELETE|TRACK) [NC]
		RewriteRule ^.* - [F]

		# Filter Suspicious Query Strings in the URL - Security > Settings > System Tweaks > Suspicious Query Strings
		RewriteCond %{QUERY_STRING} \.\.\/ [NC,OR]
		RewriteCond %{QUERY_STRING} ^.*\.(bash|git|hg|log|svn|swp|cvs) [NC,OR]
		RewriteCond %{QUERY_STRING} etc/passwd [NC,OR]
		RewriteCond %{QUERY_STRING} boot\.ini [NC,OR]
		RewriteCond %{QUERY_STRING} ftp\:  [NC,OR]
		RewriteCond %{QUERY_STRING} http\:  [NC,OR]
		RewriteCond %{QUERY_STRING} https\:  [NC,OR]
		RewriteCond %{QUERY_STRING} (\<|%3C).*script.*(\>|%3E) [NC,OR]
		RewriteCond %{QUERY_STRING} mosConfig_[a-zA-Z_]{1,21}(=|%3D) [NC,OR]
		RewriteCond %{QUERY_STRING} base64_encode.*\(.*\) [NC,OR]
		RewriteCond %{QUERY_STRING} ^.*(%24&x).* [NC,OR]
		RewriteCond %{QUERY_STRING} ^.*(127\.0).* [NC,OR]
		RewriteCond %{QUERY_STRING} ^.*(globals|encode|localhost|loopback).* [NC,OR]
		RewriteCond %{QUERY_STRING} ^.*(request|concat|insert|union|declare).* [NC]
		RewriteCond %{QUERY_STRING} !^loggedout=true
		RewriteCond %{QUERY_STRING} !^action=jetpack-sso
		RewriteCond %{QUERY_STRING} !^action=rp
		RewriteCond %{HTTP_COOKIE} !^.*wordpress_logged_in_.*$
		RewriteCond %{HTTP_REFERER} !^http://maps\.googleapis\.com(.*)$
		RewriteRule ^.* - [F]

		# Filter Non-English Characters - Security > Settings > System Tweaks > Non-English Characters
		RewriteCond %{QUERY_STRING} ^.*(%0|%A|%B|%C|%D|%E|%F).* [NC]
		RewriteRule ^.* - [F]
	
	</IfModule>
# END iThemes Security - Do not modify or remove this line

**Comment by EvanK** [comment]
@shangelina Going through the rules you provided, this is the only potential problem I can see...effectively blocking **all** access to the wordpress install page, regardless of environment:

```apache
    <files install.php>
        <IfModule mod_authz_core.c>
            Require all denied
        </IfModule>
        <IfModule !mod_authz_core.c>
            Order allow,deny
            Deny from all
        </IfModule>
    </files>
```

If you remove that, you should regain access to the install page on your development environment.

If that doesn't accomplish what you intended, I'd suggest [manually disabling the plugin](http://www.thehostingnews.com/how-to-manually-disable-a-wordpress-plugin.html), and then removing all the htaccess rules that it created

**Comment by shangelina** [comment]
Thanks for all the help! the problem was this line  
# Disable Directory Browsing - Security > Settings > System Tweaks > Directory Browsing
    Options -Indexes
it appears when you choose with itheme security you chose to block http request method (which is a thing that ITS suggest you to do! °_°
