### ISSUE TITLE
Investigate using mod_pagespeed

### ISSUE THREAD

**Issue by ericclemmons** [genesis/wordpress#52]
> https://developers.google.com/speed/pagespeed/module

This was a decent option ~3 years ago when I last reviewed it, but is probably significantly more useful now.

If anything, the automatic compilation/minification of localized assets & reduction of images would be extremely useful for performance.  Doing it anywhere else would not be nearly as performant.

**Comment by EvanK** [comment]
This will need to be implemented in Evolution, if at all
