### ISSUE TITLE
Remove rewriting of URLs via output buffer

### ISSUE THREAD

**Issue by ericclemmons** [genesis/wordpress#76]
> https://github.com/genesis/wordpress/blob/master/src/Genesis.php#L35-L41

If constants are set correctly (which they *should* be!), then there should be no need to rewrite the HTML upon delivery.  The only reason this existed was because of sites using hard-coded URLs, but that behavior should not be encouraged at all.

If anything, URLs should omit the domain & just use the path.

**This is a BC change, as it breaks expected behavior for existing projects**

**Comment by EvanK** [comment]
Still an issue for evolution/wordpress#37

We'll be solving it there. Closing out...
